version: '3.8'

services:
  ai-delver-intelligence:
    image: ai-delver-intelligence:dev
    container_name: ai-delver-intelligence
    build:
      context: .
      dockerfile: ai-delver-intelligence/docker/Dockerfile
      target: builder-dev
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        UID: ${UID}
        GID: ${GID}
    ports:
      - "8001:8001"
    working_dir: /app
    user: "${UID}:${GID}"
    shm_size: ${AI_SHM_SIZE}

    volumes:
      - ./ai-delver-intelligence:/app
      - ./pytiling-lib:/pytiling-lib
      - ./ai-delver-runtime:/ai-delver-runtime
      - ./ai-delver-level:/ai-delver-level
      - ./pyglet-dragonbones-lib:/pyglet-dragonbones-lib
      - ./assets:/assets
      - ./ai-delver-intelligence/logs:/app/logs
    environment:
      - PYTHONPATH=/ai-delver-runtime:/ai-delver-runtime/runtime:/ai-delver-level:/pytiling-lib:/pyglet-dragonbones-lib
      - CONTAINER_COMMAND
      - AI_BATCH_SIZE=${AI_BATCH_SIZE}
      
    command: sh -c "${CONTAINER_COMMAND}"
    stdin_open: true
    tty: true

    deploy:
      resources:
        limits:
          memory: ${AI_MEMORY_LIMIT}